modulation        = "fm"
sample_rate       = 9_600_000
center_freq       = 98_000_000
channel_rate      = 480_000
audio_rate        = 48_000
audio_gain        = 1.0
spectrum_fft_size = 1024
spectrum_fps      = 20
api_base          = "http://localhost:8020"
